/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_bsdconv_Bsdconv */

#ifndef _Included_io_bsdconv_Bsdconv
#define _Included_io_bsdconv_Bsdconv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_bsdconv_Bsdconv
 * Method:    _bsdconv_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_bsdconv_Bsdconv__1bsdconv_1create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_bsdconv_Bsdconv
 * Method:    _bsdconv_conv
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_bsdconv_Bsdconv__1bsdconv_1conv
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_bsdconv_Bsdconv
 * Method:    _bsdconv_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_bsdconv_Bsdconv__1bsdconv_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_bsdconv_Bsdconv
 * Method:    _bsdconv_pack
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_bsdconv_Bsdconv__1bsdconv_1pack
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
