/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_buganini_Bsdconv */

#ifndef _Included_io_buganini_Bsdconv
#define _Included_io_buganini_Bsdconv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_buganini_Bsdconv
 * Method:    _bsdconv_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_buganini_Bsdconv__1bsdconv_1create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_buganini_Bsdconv
 * Method:    _bsdconv_pack
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_buganini_Bsdconv__1bsdconv_1pack
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
